<?php

use Illuminate\Database\Seeder;

class AlatBeratTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('alat_berat')->delete();
        
        \DB::table('alat_berat')->insert(array (
            0 => 
            array (
                'id' => 1,
                'id_kategori' => 1,
                'nomor_lambung' => '12',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            1 => 
            array (
                'id' => 2,
                'id_kategori' => 1,
                'nomor_lambung' => '107',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            2 => 
            array (
                'id' => 3,
                'id_kategori' => 1,
                'nomor_lambung' => '108',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            3 => 
            array (
                'id' => 4,
                'id_kategori' => 1,
                'nomor_lambung' => '129',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            4 => 
            array (
                'id' => 5,
                'id_kategori' => 1,
                'nomor_lambung' => '132',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            5 => 
            array (
                'id' => 6,
                'id_kategori' => 1,
                'nomor_lambung' => '133',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            6 => 
            array (
                'id' => 7,
                'id_kategori' => 1,
                'nomor_lambung' => '135',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            7 => 
            array (
                'id' => 9,
                'id_kategori' => 1,
                'nomor_lambung' => '137',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            8 => 
            array (
                'id' => 10,
                'id_kategori' => 3,
                'nomor_lambung' => '138',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            9 => 
            array (
                'id' => 11,
                'id_kategori' => 1,
                'nomor_lambung' => '139',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            10 => 
            array (
                'id' => 12,
                'id_kategori' => 1,
                'nomor_lambung' => '140',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            11 => 
            array (
                'id' => 13,
                'id_kategori' => 1,
                'nomor_lambung' => '141',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            12 => 
            array (
                'id' => 14,
                'id_kategori' => 1,
                'nomor_lambung' => '142',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            13 => 
            array (
                'id' => 15,
                'id_kategori' => 1,
                'nomor_lambung' => '143',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            14 => 
            array (
                'id' => 16,
                'id_kategori' => 9,
                'nomor_lambung' => '144',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            15 => 
            array (
                'id' => 17,
                'id_kategori' => 1,
                'nomor_lambung' => '148',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            16 => 
            array (
                'id' => 18,
                'id_kategori' => 1,
                'nomor_lambung' => '149',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            17 => 
            array (
                'id' => 19,
                'id_kategori' => 1,
                'nomor_lambung' => '150',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            18 => 
            array (
                'id' => 20,
                'id_kategori' => 1,
                'nomor_lambung' => '151',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            19 => 
            array (
                'id' => 21,
                'id_kategori' => 5,
                'nomor_lambung' => '155',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            20 => 
            array (
                'id' => 22,
                'id_kategori' => 1,
                'nomor_lambung' => '156',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            21 => 
            array (
                'id' => 23,
                'id_kategori' => 3,
                'nomor_lambung' => '158',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            22 => 
            array (
                'id' => 24,
                'id_kategori' => 1,
                'nomor_lambung' => '159',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            23 => 
            array (
                'id' => 25,
                'id_kategori' => 1,
                'nomor_lambung' => '162',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            24 => 
            array (
                'id' => 26,
                'id_kategori' => 1,
                'nomor_lambung' => '163',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            25 => 
            array (
                'id' => 27,
                'id_kategori' => 1,
                'nomor_lambung' => '164',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            26 => 
            array (
                'id' => 28,
                'id_kategori' => 1,
                'nomor_lambung' => '165',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            27 => 
            array (
                'id' => 29,
                'id_kategori' => 1,
                'nomor_lambung' => '168',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            28 => 
            array (
                'id' => 30,
                'id_kategori' => 1,
                'nomor_lambung' => '169',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            29 => 
            array (
                'id' => 31,
                'id_kategori' => 1,
                'nomor_lambung' => '171',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            30 => 
            array (
                'id' => 32,
                'id_kategori' => 2,
                'nomor_lambung' => '172',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            31 => 
            array (
                'id' => 33,
                'id_kategori' => 1,
                'nomor_lambung' => '172',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            32 => 
            array (
                'id' => 34,
                'id_kategori' => 1,
                'nomor_lambung' => '174',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            33 => 
            array (
                'id' => 35,
                'id_kategori' => 1,
                'nomor_lambung' => '175',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            34 => 
            array (
                'id' => 36,
                'id_kategori' => 1,
                'nomor_lambung' => '176',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            35 => 
            array (
                'id' => 37,
                'id_kategori' => 1,
                'nomor_lambung' => '178',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            36 => 
            array (
                'id' => 38,
                'id_kategori' => 1,
                'nomor_lambung' => '179',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            37 => 
            array (
                'id' => 39,
                'id_kategori' => 9,
                'nomor_lambung' => '182',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            38 => 
            array (
                'id' => 40,
                'id_kategori' => 1,
                'nomor_lambung' => '183',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            39 => 
            array (
                'id' => 41,
                'id_kategori' => 1,
                'nomor_lambung' => '184',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            40 => 
            array (
                'id' => 42,
                'id_kategori' => 1,
                'nomor_lambung' => '187',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            41 => 
            array (
                'id' => 43,
                'id_kategori' => 1,
                'nomor_lambung' => '188',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            42 => 
            array (
                'id' => 44,
                'id_kategori' => 1,
                'nomor_lambung' => '189',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            43 => 
            array (
                'id' => 45,
                'id_kategori' => 1,
                'nomor_lambung' => '190',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            44 => 
            array (
                'id' => 46,
                'id_kategori' => 1,
                'nomor_lambung' => '191',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            45 => 
            array (
                'id' => 47,
                'id_kategori' => 1,
                'nomor_lambung' => '193',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            46 => 
            array (
                'id' => 48,
                'id_kategori' => 1,
                'nomor_lambung' => '194',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            47 => 
            array (
                'id' => 49,
                'id_kategori' => 1,
                'nomor_lambung' => '195',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            48 => 
            array (
                'id' => 50,
                'id_kategori' => 1,
                'nomor_lambung' => '196',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            49 => 
            array (
                'id' => 51,
                'id_kategori' => 1,
                'nomor_lambung' => '197',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            50 => 
            array (
                'id' => 52,
                'id_kategori' => 1,
                'nomor_lambung' => '198',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            51 => 
            array (
                'id' => 53,
                'id_kategori' => 1,
                'nomor_lambung' => '199',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            52 => 
            array (
                'id' => 54,
                'id_kategori' => 1,
                'nomor_lambung' => '200',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            53 => 
            array (
                'id' => 55,
                'id_kategori' => 1,
                'nomor_lambung' => '201',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            54 => 
            array (
                'id' => 56,
                'id_kategori' => 1,
                'nomor_lambung' => '202',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            55 => 
            array (
                'id' => 57,
                'id_kategori' => 1,
                'nomor_lambung' => '203',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            56 => 
            array (
                'id' => 58,
                'id_kategori' => 1,
                'nomor_lambung' => '205',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            57 => 
            array (
                'id' => 59,
                'id_kategori' => 1,
                'nomor_lambung' => '206',
                'nomor_polisi' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-02 16:01:30',
            ),
            58 => 
            array (
                'id' => 8,
                'id_kategori' => 1,
                'nomor_lambung' => '136',
                'nomor_polisi' => NULL,
                'status' => '0',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-02 16:01:30',
                'updated_at' => '2019-12-05 14:52:23',
            ),
        ));
        
        
    }
}