<?php

use Illuminate\Database\Seeder;

class KaruTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('karu')->delete();
        
        \DB::table('karu')->insert(array (
            0 => 
            array (
                'id' => 105,
                'nama' => 'testing',
                'no_hp' => '',
                'start_date' => '2019-11-29',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-12-29 11:06:09',
                'updated_at' => NULL,
                'nik' => '',
                'id_gudang' => NULL,
            ),
            1 => 
            array (
                'id' => 27,
                'nama' => 'Abdul Rohman',
                'no_hp' => '08999',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => '2020-01-15 16:06:31',
                'nik' => 'T.284472',
                'id_gudang' => 4,
            ),
            2 => 
            array (
                'id' => 11,
                'nama' => 'Agus Wikanto',
                'no_hp' => '',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => '2020-01-15 16:08:37',
                'nik' => 'T 253562',
                'id_gudang' => 6,
            ),
            3 => 
            array (
                'id' => 4,
                'nama' => 'Parno',
                'no_hp' => '',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => '2020-01-16 13:19:16',
                'nik' => '2190416',
                'id_gudang' => 12,
            ),
            4 => 
            array (
                'id' => 7,
                'nama' => 'Moch. Jubaidi',
                'no_hp' => '',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => '2020-01-17 10:13:08',
                'nik' => 'T 253572',
                'id_gudang' => 2,
            ),
            5 => 
            array (
                'id' => 1,
                'nama' => 'Imam Subekti',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => '2180390',
                'id_gudang' => NULL,
            ),
            6 => 
            array (
                'id' => 2,
                'nama' => 'Totok Hardjito',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.253563',
                'id_gudang' => NULL,
            ),
            7 => 
            array (
                'id' => 3,
                'nama' => 'Wondo Sudibyo',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.253576',
                'id_gudang' => NULL,
            ),
            8 => 
            array (
                'id' => 5,
                'nama' => 'Mulyo Hari Irianto',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T243131',
                'id_gudang' => NULL,
            ),
            9 => 
            array (
                'id' => 6,
                'nama' => 'Achmad Fadoli',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => '2180390',
                'id_gudang' => NULL,
            ),
            10 => 
            array (
                'id' => 8,
                'nama' => 'Wito',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T243139',
                'id_gudang' => NULL,
            ),
            11 => 
            array (
                'id' => 9,
                'nama' => 'Suwito',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T242774',
                'id_gudang' => NULL,
            ),
            12 => 
            array (
                'id' => 10,
                'nama' => 'Moesidi',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T284199',
                'id_gudang' => NULL,
            ),
            13 => 
            array (
                'id' => 12,
                'nama' => 'Sayudi',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.253554',
                'id_gudang' => NULL,
            ),
            14 => 
            array (
                'id' => 13,
                'nama' => 'Said Priyanto',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T 243134',
                'id_gudang' => NULL,
            ),
            15 => 
            array (
                'id' => 14,
                'nama' => 'Wiji Mulyo',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T284471',
                'id_gudang' => NULL,
            ),
            16 => 
            array (
                'id' => 15,
                'nama' => 'Jimat',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T. 253542',
                'id_gudang' => NULL,
            ),
            17 => 
            array (
                'id' => 16,
                'nama' => 'Mulyono',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.232196',
                'id_gudang' => NULL,
            ),
            18 => 
            array (
                'id' => 17,
                'nama' => 'Sujud Triwibowo',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T284454',
                'id_gudang' => NULL,
            ),
            19 => 
            array (
                'id' => 18,
                'nama' => 'Kholis',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.284318',
                'id_gudang' => NULL,
            ),
            20 => 
            array (
                'id' => 19,
                'nama' => 'Elkana Stiarsa',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T253722',
                'id_gudang' => NULL,
            ),
            21 => 
            array (
                'id' => 20,
                'nama' => 'Subeki',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.253546',
                'id_gudang' => NULL,
            ),
            22 => 
            array (
                'id' => 21,
                'nama' => 'Bambang Dwi Antoni',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T284347',
                'id_gudang' => NULL,
            ),
            23 => 
            array (
                'id' => 22,
                'nama' => 'M. Ihwan',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T. 243123',
                'id_gudang' => NULL,
            ),
            24 => 
            array (
                'id' => 23,
                'nama' => 'Muhammad Anwar',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T. 284395',
                'id_gudang' => NULL,
            ),
            25 => 
            array (
                'id' => 24,
                'nama' => 'Gatot Dwi R',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.284385',
                'id_gudang' => NULL,
            ),
            26 => 
            array (
                'id' => 25,
                'nama' => 'Yohanes Joni Welerubun',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T284298',
                'id_gudang' => NULL,
            ),
            27 => 
            array (
                'id' => 26,
                'nama' => 'Ripa\'i',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.284338 ',
                'id_gudang' => NULL,
            ),
            28 => 
            array (
                'id' => 28,
                'nama' => 'Samiran',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T243131',
                'id_gudang' => NULL,
            ),
            29 => 
            array (
                'id' => 29,
                'nama' => 'Budi Hariyanto',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T284343',
                'id_gudang' => NULL,
            ),
            30 => 
            array (
                'id' => 30,
                'nama' => 'Muzammil',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.284387',
                'id_gudang' => NULL,
            ),
            31 => 
            array (
                'id' => 31,
                'nama' => 'Lukman Hakim',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T. 284388',
                'id_gudang' => NULL,
            ),
            32 => 
            array (
                'id' => 32,
                'nama' => 'Ali Mashudi',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.314646',
                'id_gudang' => NULL,
            ),
            33 => 
            array (
                'id' => 33,
                'nama' => 'Novian Dwi Cahyo',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.545444',
                'id_gudang' => NULL,
            ),
            34 => 
            array (
                'id' => 34,
                'nama' => 'Denny Widyo P.O',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T. 555727',
                'id_gudang' => NULL,
            ),
            35 => 
            array (
                'id' => 35,
                'nama' => 'Mohamad Hafidz Yusuf',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.555734',
                'id_gudang' => NULL,
            ),
            36 => 
            array (
                'id' => 36,
                'nama' => 'Dhimastiya Bagus D. F.',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T. 555742',
                'id_gudang' => NULL,
            ),
            37 => 
            array (
                'id' => 37,
                'nama' => 'Dandy Satriyo B.',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.555728',
                'id_gudang' => NULL,
            ),
            38 => 
            array (
                'id' => 38,
                'nama' => 'Sony Kandi Lesmana',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T555750',
                'id_gudang' => NULL,
            ),
            39 => 
            array (
                'id' => 39,
                'nama' => 'M. Irfan Mahfudin',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.555744',
                'id_gudang' => NULL,
            ),
            40 => 
            array (
                'id' => 40,
                'nama' => 'Bryan Calvin Rachmawan',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T. 555733',
                'id_gudang' => NULL,
            ),
            41 => 
            array (
                'id' => 41,
                'nama' => 'Mohammad Yusuf',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.555741',
                'id_gudang' => NULL,
            ),
            42 => 
            array (
                'id' => 42,
                'nama' => 'Yusri Roman D.',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T555743',
                'id_gudang' => NULL,
            ),
            43 => 
            array (
                'id' => 43,
                'nama' => 'Iksan Ramadan',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T. 555740',
                'id_gudang' => NULL,
            ),
            44 => 
            array (
                'id' => 44,
                'nama' => 'Lendy Tri Prasetyo',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T555731',
                'id_gudang' => NULL,
            ),
            45 => 
            array (
                'id' => 45,
                'nama' => 'Edi Waskito',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T555747',
                'id_gudang' => NULL,
            ),
            46 => 
            array (
                'id' => 46,
                'nama' => 'Luky Candra Purwadinata',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T.555729',
                'id_gudang' => NULL,
            ),
            47 => 
            array (
                'id' => 47,
                'nama' => 'Rengga Aggi P',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T. 555737',
                'id_gudang' => NULL,
            ),
            48 => 
            array (
                'id' => 48,
                'nama' => 'Arli Arrakhim',
                'no_hp' => NULL,
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'nik' => 'T. 555739',
                'id_gudang' => NULL,
            ),
        ));
        
        
    }
}