<?php

use Illuminate\Database\Seeder;

class MaterialTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('material')->delete();
        
        \DB::table('material')->insert(array (
            0 => 
            array (
                'id' => 1,
                'id_material_sap' => 1000278,
                'kategori' => 1,
                'berat' => '1000',
                'koefisien_pallet' => '1.5',
                'nama' => 'ALF3 @1000KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'id_material_sap' => 1000270,
                'kategori' => 1,
                'berat' => '20',
                'koefisien_pallet' => '1.5',
                'nama' => 'ALF3 @20KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'id_material_sap' => 1000271,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'ALF3 @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'id_material_sap' => 5000281,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
            'nama' => 'JUMBO BAG (BEKAS) --  FLEXIBLE-CONTAINER',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'id_material_sap' => 1000274,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'Kaptan @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'id_material_sap' => 1000301,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 0-14-14+8,1Mg MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'id_material_sap' => 1000064,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 10-0-30 +0,6B NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'id_material_sap' => 1000299,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 10-11-10+4Mg MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'id_material_sap' => 1000067,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 10-5-30 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'id_material_sap' => 1000068,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 11,6-0-27 MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'id_material_sap' => 1000069,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 11-7-27 NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'id_material_sap' => 1000070,
                'kategori' => 1,
                'berat' => '20',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-11-20 +0,03B FUS NS @20KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'id_material_sap' => 1000071,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-11-20 +0,03B FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'id_material_sap' => 1000128,
                'kategori' => 1,
                'berat' => '20',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-11-20 +1Mg+0,2B FUS NS @20KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'id_material_sap' => 1000132,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-11-20 +1Mg+0,2B FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'id_material_sap' => 1000074,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-12-17 +2Mg FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'id_material_sap' => 1000079,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-12-17 +2Mg+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'id_material_sap' => 1000048,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-12-17+2Mg CHM CRH',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'id_material_sap' => 1000095,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-12-17+2Mg CHM NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'id_material_sap' => 1000298,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-12-17+2Mg MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'id_material_sap' => 1000038,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-12-17+2Mg+B MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'id_material_sap' => 1000297,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-12-17+2Mg+TE MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'id_material_sap' => 1000515,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-12-17+4Mg FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'id_material_sap' => 1000094,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-24-12 CHM CRH',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'id_material_sap' => 1000179,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-24-12 CHM NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'id_material_sap' => 1000083,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-6-22 +3Mg FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'id_material_sap' => 1000303,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-6-22+3Mg MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'id_material_sap' => 1000035,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 12-6-22+3Mg+TE MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'id_material_sap' => 1000089,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 13-6-26 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'id_material_sap' => 1000091,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 13-6-27 +4Mg NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'id_material_sap' => 1000092,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 13-6-27 +4Mg+0,65B NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'id_material_sap' => 1000304,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 13-6-27+3Mg+0,65B MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'id_material_sap' => 1000101,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 13-7-25 +1TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'id_material_sap' => 1000102,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 13-7-25 +1TE+HA NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'id_material_sap' => 1000045,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 13-8-27 MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'id_material_sap' => 1000419,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-10-21+2Mg+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'id_material_sap' => 1000409,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-10-23+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'id_material_sap' => 1000381,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-13-9+2,5Mg CHM NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'id_material_sap' => 1000392,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-13-9+2,5Mg FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'id_material_sap' => 1000268,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-14-14 CHM CRH',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'id_material_sap' => 1000109,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-34-0 CHM CRH',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'id_material_sap' => 1000110,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-34-0 CHM NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'id_material_sap' => 1000412,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-6-27+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'id_material_sap' => 1000113,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-7-24 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'id_material_sap' => 1001341,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-7-25+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'id_material_sap' => 1000410,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-7-26+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'id_material_sap' => 1000117,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-8-23 NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'id_material_sap' => 1000420,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-8-23+2Mg+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'id_material_sap' => 1000411,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-8-25+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'id_material_sap' => 1000418,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-9-22+2Mg+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'id_material_sap' => 1000408,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 14-9-24+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'id_material_sap' => 1000521,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-10-18 +2Mg FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'id_material_sap' => 1000504,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-10-18+4Mg FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'id_material_sap' => 1000338,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-10-19 +2Mg+3Ca NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'id_material_sap' => 1000121,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-10-19 +2Mg+3CaO+1S+1TE NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'id_material_sap' => 1000413,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-10-22+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'id_material_sap' => 1000125,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-10-23 +0,5TE NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'id_material_sap' => 1000127,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-10-23 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'id_material_sap' => 1000130,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-11-22 +4Mg+0,6B NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'id_material_sap' => 1000131,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-12-22 +0,5TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'id_material_sap' => 1000133,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-12-22 +1TE NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'id_material_sap' => 1000135,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-15 CHM CRH NAT Export',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'id_material_sap' => 1000293,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-15 CHM CRH PG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'id_material_sap' => 1000136,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-15 CHM NS @50KG Export',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'id_material_sap' => 1000141,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-15 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'id_material_sap' => 1000145,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-15 KEBOMAS CHM NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'id_material_sap' => 1000047,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-15 MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'id_material_sap' => 1000147,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-15 SUB @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'id_material_sap' => 1000288,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-15 UPSUS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'id_material_sap' => 1000522,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-15,6 +4Mg FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'id_material_sap' => 1000378,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-15+9S+0,2Zn CHM CRH',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'id_material_sap' => 1000148,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-17 +4Mg+0,5B NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'id_material_sap' => 1000150,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-6 +4Mg FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'id_material_sap' => 1000049,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-6+4Mg CHM CRH',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'id_material_sap' => 1000107,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-6+4Mg CHM NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'id_material_sap' => 1000309,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-15-6+4Mg MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'id_material_sap' => 1000520,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-2-17 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'id_material_sap' => 1000033,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-33 MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'id_material_sap' => 1000155,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-4-21 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'id_material_sap' => 1000910,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-6-24 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'id_material_sap' => 1000376,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-7-23 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'id_material_sap' => 1001342,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-7-24+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'id_material_sap' => 1000156,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-8-21 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'id_material_sap' => 1000157,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-8-22 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'id_material_sap' => 1000417,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-8-24+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'id_material_sap' => 1000414,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-8-25+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'id_material_sap' => 1000407,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-9-23+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'id_material_sap' => 1000416,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 15-9-24+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'id_material_sap' => 1000160,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-10-21 +0,5TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'id_material_sap' => 1000163,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-11-20 +0,5TE NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'id_material_sap' => 1000165,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-11-21 +0,5B+0,25Zn NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'id_material_sap' => 1000167,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-11-21 +1TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'id_material_sap' => 1000169,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-11-21 +1TE+0,5B NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'id_material_sap' => 1000171,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-12-21 +0,5TE NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'id_material_sap' => 1000337,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-12-21 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'id_material_sap' => 1001326,
                'kategori' => 1,
                'berat' => '20',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-16-16 NITRAT FUS NS @20KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'id_material_sap' => 1001331,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-16-16 NITRAT FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'id_material_sap' => 1000177,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-16-8 +1TE CHM CRH',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'id_material_sap' => 1000178,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-16-8 +1TE CHM NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'id_material_sap' => 1000295,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-16-8 CHM @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'id_material_sap' => 1000294,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-16-8 CHM CRH',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'id_material_sap' => 1000181,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-20-0 +13S CHM CRH',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'id_material_sap' => 1000182,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-20-0 +13S CHM NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'id_material_sap' => 1000516,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-4-25 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'id_material_sap' => 1000637,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-5-24 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'id_material_sap' => 1000687,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-5-24 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'id_material_sap' => 1000185,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-6-23 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'id_material_sap' => 1000415,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 16-7-24+TE FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'id_material_sap' => 1000375,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 17-0-28 MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'id_material_sap' => 1000189,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 17-0-28 NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'id_material_sap' => 1000009,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 17-33 MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'id_material_sap' => 1000517,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 17-5-23 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'id_material_sap' => 1000193,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 17-6-22 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'id_material_sap' => 1000025,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 17-6-29 MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'id_material_sap' => 1000194,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 17-7-20 FUS NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'id_material_sap' => 1000302,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 18-10-22+0,5TE MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'id_material_sap' => 1000041,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 19-8-10+3Mg+2Ca MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'id_material_sap' => 1000043,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 19-9-19 MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'id_material_sap' => 1000204,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 20-0-16 MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'id_material_sap' => 1000216,
                'kategori' => 1,
                'berat' => NULL,
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 20-20-0 +13S CHM CRH',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'id_material_sap' => 1000217,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 20-20-0 +13S CHM NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'id_material_sap' => 1000308,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 20-6-6 MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'id_material_sap' => 1000307,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 20-9-15 MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'id_material_sap' => 1000222,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 24-12-10 +HA MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'id_material_sap' => 1000296,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 27-6-10+3Mg MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'id_material_sap' => 1000306,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 27-6-14+2Mg MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'id_material_sap' => 1000305,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 27-6-14+2Mg+HA MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'id_material_sap' => 1000300,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 6,95-6,34-15,84+2,38Mg MIX @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'id_material_sap' => 1000393,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK 7-6-34+Te MIX NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'id_material_sap' => 1000384,
                'kategori' => 1,
                'berat' => '1000',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK PHONSKA PLUS @1 ton',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'id_material_sap' => 1000383,
                'kategori' => 1,
                'berat' => '25',
                'koefisien_pallet' => '1.5',
                'nama' => 'NPK PHONSKA PLUS @25KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'id_material_sap' => 1000200,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'SP 36 NS @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'id_material_sap' => 1000037,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'Urea PRL NS @50 KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'id_material_sap' => 1000036,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'Urea SUB @50 KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'id_material_sap' => 1000140,
                'kategori' => 1,
                'berat' => '1000',
                'koefisien_pallet' => '1.5',
                'nama' => 'ZA NS @1000KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'id_material_sap' => 1000058,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'ZA NS @50 KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'id_material_sap' => 1000057,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'ZA SUB @50 KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'id_material_sap' => 1000627,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
            'nama' => 'ZK Granul NS @50KG (Petrokalimas)',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'id_material_sap' => 1000382,
                'kategori' => 1,
                'berat' => '1000',
                'koefisien_pallet' => '1.5',
                'nama' => 'ZK NS @1 TON',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'id_material_sap' => 1000060,
                'kategori' => 1,
                'berat' => '20',
                'koefisien_pallet' => '1.5',
                'nama' => 'ZK NS @20 KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'id_material_sap' => 1000651,
                'kategori' => 1,
                'berat' => '25',
                'koefisien_pallet' => '1.5',
                'nama' => 'ZK NS @25 KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'id_material_sap' => 1000059,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'ZK NS @50 KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'id_material_sap' => 1000272,
                'kategori' => 1,
                'berat' => '50',
                'koefisien_pallet' => '1.5',
                'nama' => 'Petrocas @50KG',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'id_material_sap' => NULL,
                'kategori' => NULL,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Pallet Pupuk Plastik',
                'start_date' => NULL,
                'end_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'id_material_sap' => NULL,
                'kategori' => 2,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Pallet Pupuk Kayu ',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'id_material_sap' => NULL,
                'kategori' => 2,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Pallet ALF3 Uk. 110x110',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'id_material_sap' => NULL,
                'kategori' => 2,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Pallet ALF3 Uk. 110x140',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'id_material_sap' => NULL,
                'kategori' => 2,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Pallet ALF3 Uk. 110x110 Alas Triplex',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'id_material_sap' => NULL,
                'kategori' => 2,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Pallet ALF3 Uk. 110x140 Alas Triplex',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'id_material_sap' => NULL,
                'kategori' => 3,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Terplas ',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'id_material_sap' => NULL,
                'kategori' => 3,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Tali Rafia',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'id_material_sap' => NULL,
                'kategori' => 3,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Jarum Rafia',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'id_material_sap' => NULL,
                'kategori' => 3,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Handy Talky',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'id_material_sap' => NULL,
                'kategori' => 3,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Camera',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'id_material_sap' => NULL,
                'kategori' => 3,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Tangga Lipat',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'id_material_sap' => NULL,
                'kategori' => 3,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Water Jet',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'id_material_sap' => NULL,
                'kategori' => 3,
                'berat' => NULL,
                'koefisien_pallet' => NULL,
                'nama' => 'Vacuum Cleaner',
                'start_date' => '2019-11-22',
                'end_date' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2019-11-22 00:00:00',
                'updated_at' => NULL,
                'id_plant' => NULL,
            ),
        ));
        
        
    }
}